-- ════════════════════════════════════════════════════════════
--  Hyprland · monochrome · ROG Zephyrus G16
--  Lua config (Hyprland 0.55+).  Docs: https://wiki.hypr.land
-- ════════════════════════════════════════════════════════════

hl.config({ autogenerated = false })

---------------------------------------------------------------
--  PROGRAMS
---------------------------------------------------------------
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "wofi --show drun"
local locker      = "hyprlock"

---------------------------------------------------------------
--  MONITORS  (G16 internal panel: 2560x1600@240, 1.6 scale)
---------------------------------------------------------------
hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@240",
    position = "0x0",
    scale    = 1.6,
})
-- AOC 27G2G8: above the laptop, 1080p at max refresh (240Hz). Matched by
-- description so it works on any DP/USB-C port. Laptop is 2560x1600@1.6 =
-- 1600x1000 logical at 0x0; this monitor is 1920x1080@1.0, so y=-1080 sits it
-- directly above with left edges aligned.
hl.monitor({
    output   = "desc:AOC 27G2G8 1EKQ1JA009425",
    mode     = "1920x1080@239.96",
    position = "0x-1080",
    scale    = 1,
})
-- any other external monitor: auto place to the right at native res
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------------------------------------------------
--  AUTOSTART
---------------------------------------------------------------
hl.on("hyprland.start", function()
    -- Screensharing: export the Wayland env to systemd/dbus and bring up
    -- graphical-session.target (via hyprland-session.target) so xdg-desktop-portal
    -- can start. Without this, Google Meet/OBS screencapture hangs. See
    -- ~/.config/systemd/user/hyprland-session.target and ~/.config/xdg-desktop-portal/portals.conf
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP")
    -- REMOVED: starting hyprland-session.target pulled in graphical-session.target,
    -- which on this machine drags in KDE's kwin_wayland/plasmashell -> black screen.
    hl.exec_cmd("hyprpaper")
    -- rotate minimalist wallpapers every 5 min; Super+W skips ahead (SIGUSR1)
    hl.exec_cmd("$HOME/.config/hypr/scripts/wallpaper-cycle.sh")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("swayosd-server --style $HOME/.config/swayosd/style.css")  -- volume/brightness OSD
    hl.exec_cmd("hypridle")
    -- DISABLED: duplicate wifi tray icon. Waybar's grouped `network` module covers
    -- status + click-opens nm-connection-editor. NetworkManager daemon is unaffected.
    -- hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --watch cliphist store")   -- clipboard history daemon
    hl.exec_cmd("/opt/ghelper/ghelper")              -- G-Helper (ASUS control) -> tray
    -- Claude'O'Clock: floating agent monitor. Guard against a second instance
    -- (it binds the hook server on 127.0.0.1:22362, which only one process can hold).
    hl.exec_cmd("sh -c 'pgrep -x claudeoclock >/dev/null || claudeoclock'")
    -- waybar auto-hide: edge-triggered cursor watcher (reveal at top edge, hide below).
    -- Starts after waybar so its SIGUSR1 handler is installed first.
    hl.exec_cmd("$HOME/.config/waybar/scripts/autohide.sh")
    -- DISABLED: wl-gammarelay-rs (gamma daemon) can blank the panel with a bad ramp.
    -- hl.exec_cmd("wl-gammarelay-rs")
end)

---------------------------------------------------------------
--  ENVIRONMENT
---------------------------------------------------------------
hl.env("XCURSOR_THEME", "MacOS-Tahoe-Cursor")   -- macOS Tahoe cursors (XCursor theme in ~/.icons)
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_THEME", "Adwaita:dark")
-- Qt apps (Dolphin, etc.) -> use KDE platform theme, which reads the dark kdeglobals
hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

---------------------------------------------------------------
--  LOOK AND FEEL  (monochrome)
---------------------------------------------------------------
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 10,
        border_size = 2,
        col = {
            active_border   = "rgba(34322dff)",   -- muted stone grey (minimal)
            inactive_border = "rgba(141417ff)",   -- dark grey
        },
        resize_on_border = true,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 8,
        rounding_power = 2,
        -- rounded screen corners (black bezel fade at the panel's far corners);
        -- relative path resolves against this config's directory
        screen_shader  = "shaders/rounded-corners.glsl",
        -- frosted: windows slightly translucent so the blur shows through
        -- (fullscreen_opacity stays 1.0 by default, so video is unaffected)
        active_opacity   = 0.94,
        inactive_opacity = 0.88,

        shadow = {
            enabled      = true,
            range        = 16,
            render_power = 3,
            color        = "rgba(00000055)",
        },

        blur = {
            enabled      = true,
            size         = 8,
            passes       = 3,
            new_optimizations = true,
            vibrancy     = 0.10,
            noise        = 0.015,
        },
    },

    animations = { enabled = true },

    dwindle = {
        preserve_split = true,
    },

    master = { new_status = "master" },

    misc = {
        force_default_wallpaper = 0,      -- no anime mascot
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,  -- no version/splash text at bottom
        background_color        = "rgb(000000)",  -- pure black backdrop
        focus_on_activate       = true,
    },
})

---------------------------------------------------------------
--  ANIMATIONS  (clean + quick)
---------------------------------------------------------------
hl.curve("snappy",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
hl.curve("smooth",  { type = "bezier", points = { {0.23, 1},   {0.32, 1}  } })

hl.animation({ leaf = "global",     enabled = true, speed = 7,   bezier = "smooth" })
hl.animation({ leaf = "windows",    enabled = true, speed = 6,   bezier = "snappy", style = "popin 90%" })
hl.animation({ leaf = "border",     enabled = true, speed = 8,   bezier = "smooth" })
hl.animation({ leaf = "fade",       enabled = true, speed = 7,   bezier = "smooth" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6,   bezier = "smooth", style = "slide" })
hl.animation({ leaf = "layers",     enabled = true, speed = 5,   bezier = "smooth", style = "slide" })

---------------------------------------------------------------
--  INPUT
---------------------------------------------------------------
hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0,
        touchpad = {
            natural_scroll  = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
            tap_to_click    = true,
        },
    },
    gestures = {},
})

-- 3-finger horizontal swipe → switch workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

---------------------------------------------------------------
--  KEYBINDINGS
---------------------------------------------------------------
local mod = "SUPER"

-- apps / session
hl.bind(mod .. " + Return",        hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + Q",             hl.dsp.window.close())
hl.bind(mod .. " + E",             hl.dsp.exec_cmd(fileManager))
hl.bind(mod .. " + R",             hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + L",             hl.dsp.exec_cmd(locker))
hl.bind(mod .. " + Escape",        hl.dsp.exec_cmd("wlogout -b 5"))   -- power menu
hl.bind(mod .. " + SHIFT + Q",     hl.dsp.exit())

-- utilities
hl.bind(mod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))  -- clipboard history
hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))                                              -- color picker -> clipboard
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("pkill -INT wf-recorder || wf-recorder -g \"$(slurp)\" -f \"$HOME/Videos/rec-$(date +%s).mp4\""))  -- screen record toggle

-- workspace overview (needs hyprexpo plugin: hyprpm enable hyprexpo)
hl.bind(mod .. " + grave", hl.dsp.exec_raw("hyprexpo:expo", "toggle"))

-- G-Helper (ASUS control panel)
hl.bind(mod .. " + G", hl.dsp.exec_cmd("/opt/ghelper/ghelper"))

-- restart bar + auto-hide watcher (saves copy-pasting the restart command)
hl.bind(mod .. " + SHIFT + B", hl.dsp.exec_cmd("$HOME/.config/waybar/scripts/restart-bar.sh"))

-- next wallpaper (signals the 5-min cycler to advance immediately)
hl.bind(mod .. " + W", hl.dsp.exec_cmd("pkill -USR1 -f wallpaper-cycle.sh"))

-- tools menu + keybinds help
hl.bind(mod .. " + T",     hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/tools-menu.sh"))
hl.bind(mod .. " + slash", hl.dsp.exec_cmd("kitty --class keybinds-help -e \"$HOME/.config/hypr/scripts/keybinds.sh\""))

-- OLED care
-- NOTE: a manual dpms-off "blank screen" bind was removed — this panel does not
-- reliably wake from dpms-off on the current driver. Use Super+L to lock instead.
hl.bind(mod .. " + SHIFT + O", hl.dsp.exec_cmd("kitty --class oled-refresh --start-as=fullscreen -e \"$HOME/.config/hypr/scripts/oled-refresh.sh\" 30"))  -- pixel-refresh wash

-- window management
hl.bind(mod .. " + V",             hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F",             hl.dsp.window.fullscreen())
hl.bind(mod .. " + J",             hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + C",             hl.dsp.window.center())

-- focus
hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- move window in layout
hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- virtual desktops: SUPER + [1-0] switch, SUPER+SHIFT + [1-0] move window
for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- scratchpad  (Super+Shift+S was moved to Super+minus because the laptop's
-- dedicated screenshot key emits Super+Shift+S — that now screenshots, see below)
hl.bind(mod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + minus",     hl.dsp.window.move({ workspace = "special:magic" }))

-- workspace scroll
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- MX Master 4 gesture button (logiops, /etc/logid.cfg): hold thumb button +
-- move mouse left/right -> logid injects Super+Ctrl+Left/Right -> switch
-- workspace. Tap without moving sends Super+grave (hyprexpo overview above).
hl.bind(mod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + left",  hl.dsp.focus({ workspace = "e-1" }))

-- mouse drag / resize
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- screenshots (grim + slurp + wl-clipboard)
hl.bind("Print",             hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind("SHIFT + Print",     hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(mod .. " + Print",   hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"$HOME/Pictures/shot-$(date +%s).png\""))
-- laptop's dedicated screenshot key (it emits Super+Shift+S, the Windows snip
-- shortcut): region select -> save to ~/Pictures AND copy to clipboard
hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | tee \"$HOME/Pictures/shot-$(date +%s).png\" | wl-copy"))

-- volume / mic
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise --max-volume 100"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"),                  { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),            { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),             { locked = true })

-- brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/brightness.sh up"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/brightness.sh down"), { locked = true, repeating = true })

-- media
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- media (Super combos): . = next, , = previous, P = play/pause
-- (Super+P replaced the old window 'pseudo' bind)
hl.bind(mod .. " + period", hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind(mod .. " + comma",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
hl.bind(mod .. " + P",      hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

---------------------------------------------------------------
--  LAYER RULES  (frosted shell surfaces)
---------------------------------------------------------------
-- ignore_alpha skips (near-)fully-transparent pixels, so only the visible
-- pills/panels get frosted — not the empty space around them.
hl.layer_rule({
    name  = "blur-waybar",
    match = { namespace = "^(waybar)$" },
    blur  = true,
    ignore_alpha = 0.1,
})
-- NOTE: no layer rule for wofi — its GTK3 layer surface renders opaque
-- (per-pixel alpha never reaches the compositor on this GTK), so blur had
-- nothing to show. Instead wofi runs with normal_window=true (wofi config)
-- and gets frosted through the wofi-frost *window* rule below, where
-- Hyprland's opacity multiply works regardless of the buffer's alpha.
hl.layer_rule({
    name  = "blur-mako",
    match = { namespace = "^(notifications)$" },
    blur  = true,
    ignore_alpha = 0.1,
})
hl.layer_rule({
    name  = "blur-swayosd",
    match = { namespace = "^(swayosd)$" },
    blur  = true,
    ignore_alpha = 0.1,
})
hl.layer_rule({
    name  = "blur-wlogout",
    match = { namespace = "^(wlogout)$" },
    blur  = true,
    ignore_alpha = 0.1,
})

---------------------------------------------------------------
--  WINDOW RULES
---------------------------------------------------------------
hl.window_rule({
    name  = "suppress-maximize",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

-- float common dialogs
hl.window_rule({
    name  = "float-dialogs",
    match = { class = "^(pavucontrol|nm-connection-editor|blueman-manager)$" },
    float = true,
})

-- wofi as a frosted floating window (see layer-rule note above)
hl.window_rule({
    name  = "wofi-frost",
    match = { class = "^(wofi)$" },
    float = true,
    center = true,
    opacity = 0.85,
    stay_focused = true,
})

-- G-Helper: floating, docked top-right and flush to the top so its
-- full-height window fits the screen exactly (it won't shrink below 1000px).
hl.window_rule({
    name  = "ghelper-float",
    match = { class = "^(ghelper)$" },
    float = true,
    move  = "monitor_w-476 0",
})

-- OLED pixel-refresh window: borderless, no rounding, no animation
hl.window_rule({
    name  = "oled-refresh",
    match = { class = "^(oled-refresh)$" },
    border_size = 0,
    rounding    = 0,
    no_anim     = true,
})

-- Keybinds help: floating, centered, sized to fit the cheatsheet
hl.window_rule({
    name  = "keybinds-help",
    match = { class = "^(keybinds-help)$" },
    float = true,
    size  = "720 880",
    center = true,
})

-- yt-dlp download window: floating, centered
hl.window_rule({
    name  = "yt-dlp-dl",
    match = { class = "^(yt-dlp-dl)$" },
    float = true,
    size  = "900 560",
    center = true,
})

-- Claude'O'Clock: floating always-on-top widget, docked top-right across all
-- workspaces. The app owns its own size (420 wide; 600 tall, or ~44 when
-- collapsed to its titlebar), so no size rule here — just float, pin and dock
-- it 20px from the right edge and 40px from the top (monitor_w is the monitor's
-- logical width, 1600 on the G16 at 1.6 scale).
hl.window_rule({
    name  = "claudeoclock",
    match = { class = "^(claudeoclock)$" },
    float = true,
    pin   = true,
    size  = "420 600",
    move  = "monitor_w-440 40",
})