-- ════════════════════════════════════════════════════════════
--  Hyprland · monochrome · ROG Zephyrus G16
--  Lua config (Hyprland 0.55+).  Docs: https://wiki.hypr.land
-- ════════════════════════════════════════════════════════════

hl.config({ autogenerated = false })

---------------------------------------------------------------
--  PROGRAMS
---------------------------------------------------------------
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "wofi --show drun"
local locker      = "hyprlock"

---------------------------------------------------------------
--  MONITORS  (G16 internal panel: 2560x1600@240, 1.6 scale)
---------------------------------------------------------------
hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@240",
    position = "0x0",
    scale    = 1.6,
})
-- any external monitor: auto place to the right at native res
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------------------------------------------------
--  AUTOSTART
---------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --watch cliphist store")   -- clipboard history daemon
    hl.exec_cmd("hyprpm reload -n")                  -- load plugins (hyprexpo) if installed
    hl.exec_cmd("/opt/ghelper/ghelper")              -- G-Helper (ASUS control) -> tray
    -- overlap-free waybar auto-hide; delayed start so waybar is fully up first
    hl.exec_cmd("sleep 5 && $HOME/.config/waybar/scripts/autohide.sh")
end)

---------------------------------------------------------------
--  ENVIRONMENT
---------------------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_THEME", "Adwaita:dark")
-- Qt apps (Dolphin, etc.) -> use KDE platform theme, which reads the dark kdeglobals
hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

---------------------------------------------------------------
--  LOOK AND FEEL  (monochrome)
---------------------------------------------------------------
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 10,
        border_size = 2,
        col = {
            active_border   = "rgba(e8e8e8ff)",   -- near-white
            inactive_border = "rgba(2a2a2eff)",   -- dark grey
        },
        resize_on_border = true,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 8,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 0.96,

        shadow = {
            enabled      = true,
            range        = 16,
            render_power = 3,
            color        = "rgba(00000055)",
        },

        blur = {
            enabled      = true,
            size         = 6,
            passes       = 3,
            new_optimizations = true,
            vibrancy     = 0.10,
            noise        = 0.015,
        },
    },

    animations = { enabled = true },

    dwindle = {
        preserve_split = true,
    },

    master = { new_status = "master" },

    misc = {
        force_default_wallpaper = 0,      -- no anime mascot
        disable_hyprland_logo   = true,
        focus_on_activate       = true,
    },
})

---------------------------------------------------------------
--  ANIMATIONS  (clean + quick)
---------------------------------------------------------------
hl.curve("snappy",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
hl.curve("smooth",  { type = "bezier", points = { {0.23, 1},   {0.32, 1}  } })

hl.animation({ leaf = "global",     enabled = true, speed = 7,   bezier = "smooth" })
hl.animation({ leaf = "windows",    enabled = true, speed = 6,   bezier = "snappy", style = "popin 90%" })
hl.animation({ leaf = "border",     enabled = true, speed = 8,   bezier = "smooth" })
hl.animation({ leaf = "fade",       enabled = true, speed = 7,   bezier = "smooth" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6,   bezier = "smooth", style = "slide" })

---------------------------------------------------------------
--  INPUT
---------------------------------------------------------------
hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0,
        touchpad = {
            natural_scroll  = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
            tap_to_click    = true,
        },
    },
    gestures = {},
})

-- 3-finger horizontal swipe → switch workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

---------------------------------------------------------------
--  KEYBINDINGS
---------------------------------------------------------------
local mod = "SUPER"

-- apps / session
hl.bind(mod .. " + Return",        hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + Q",             hl.dsp.window.close())
hl.bind(mod .. " + E",             hl.dsp.exec_cmd(fileManager))
hl.bind(mod .. " + R",             hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + L",             hl.dsp.exec_cmd(locker))
hl.bind(mod .. " + Escape",        hl.dsp.exec_cmd("wlogout -b 5"))   -- power menu
hl.bind(mod .. " + SHIFT + Q",     hl.dsp.exit())

-- utilities
hl.bind(mod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))  -- clipboard history
hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))                                              -- color picker -> clipboard
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("pkill -INT wf-recorder || wf-recorder -g \"$(slurp)\" -f \"$HOME/Videos/rec-$(date +%s).mp4\""))  -- screen record toggle

-- workspace overview (needs hyprexpo plugin: hyprpm enable hyprexpo)
hl.bind(mod .. " + grave", hl.dsp.exec_raw("hyprexpo:expo", "toggle"))

-- G-Helper (ASUS control panel)
hl.bind(mod .. " + G", hl.dsp.exec_cmd("/opt/ghelper/ghelper"))

-- tools menu + keybinds help
hl.bind(mod .. " + T",     hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/tools-menu.sh"))
hl.bind(mod .. " + slash", hl.dsp.exec_cmd("kitty --class keybinds-help -e \"$HOME/.config/hypr/scripts/keybinds.sh\""))

-- OLED care
hl.bind(mod .. " + O",         hl.dsp.exec_cmd("hyprctl dispatch dpms off"))   -- blank screen (wakes on input)
hl.bind(mod .. " + SHIFT + O", hl.dsp.exec_cmd("kitty --class oled-refresh --start-as=fullscreen -e \"$HOME/.config/hypr/scripts/oled-refresh.sh\" 30"))  -- pixel-refresh wash

-- window management
hl.bind(mod .. " + V",             hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F",             hl.dsp.window.fullscreen())
hl.bind(mod .. " + P",             hl.dsp.window.pseudo())
hl.bind(mod .. " + J",             hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + C",             hl.dsp.window.center())

-- focus
hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- move window in layout
hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- virtual desktops: SUPER + [1-0] switch, SUPER+SHIFT + [1-0] move window
for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- scratchpad
hl.bind(mod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- workspace scroll
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- mouse drag / resize
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- screenshots (grim + slurp + wl-clipboard)
hl.bind("Print",             hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind("SHIFT + Print",     hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(mod .. " + Print",   hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"$HOME/Pictures/shot-$(date +%s).png\""))

-- volume / mic
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true })

-- brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- media
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

---------------------------------------------------------------
--  WINDOW RULES
---------------------------------------------------------------
hl.window_rule({
    name  = "suppress-maximize",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

-- float common dialogs
hl.window_rule({
    name  = "float-dialogs",
    match = { class = "^(pavucontrol|nm-connection-editor|blueman-manager)$" },
    float = true,
})

-- G-Helper: floating, docked top-right and flush to the top so its
-- full-height window fits the screen exactly (it won't shrink below 1000px).
hl.window_rule({
    name  = "ghelper-float",
    match = { class = "^(ghelper)$" },
    float = true,
    move  = "monitor_w-476 0",
})

-- OLED pixel-refresh window: borderless, no rounding, no animation
hl.window_rule({
    name  = "oled-refresh",
    match = { class = "^(oled-refresh)$" },
    border_size = 0,
    rounding    = 0,
    no_anim     = true,
})

-- Keybinds help: floating, centered, sized to fit the cheatsheet
hl.window_rule({
    name  = "keybinds-help",
    match = { class = "^(keybinds-help)$" },
    float = true,
    size  = "720 880",
    center = true,
})

-- yt-dlp download window: floating, centered
hl.window_rule({
    name  = "yt-dlp-dl",
    match = { class = "^(yt-dlp-dl)$" },
    float = true,
    size  = "900 560",
    center = true,
})